Fix bootstrap migration issues
I faced the following migration troubles at project bootstrapping.

```
 % script/db_create

Sequelize CLI [Node: 7.6.0, CLI: 4.1.1, ORM: 4.42.0]

Loaded configuration file "db/config.json".
Using environment "development".
Database slack-dev created.

Sequelize CLI [Node: 7.6.0, CLI: 4.1.1, ORM: 4.42.0]

Loaded configuration file "db/config.json".
Using environment "development".
== 20171120191721-create-installation: migrating =======
== 20171120191721-create-installation: migrated (0.045s)

== 20171121145413-create-user: migrating =======
== 20171121145413-create-user: migrated (0.049s)

== 20171124173600-create-slack-user: migrating =======
== 20171124173600-create-slack-user: migrated (0.046s)

== 20171124183600-create-git-hub-user: migrating =======
== 20171124183600-create-git-hub-user: migrated (0.041s)

== 20171127144600-add-github-user-access-token: migrating =======

ERROR: Unexpected token )
```

I assumed such the error occurring due to miss of the words `async`
and `await` in some migration files.

I add these missing words to fix errors.